name: Test
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        environment: ["python-310", "python-311", "python-312", "python-313"]
        os: ["ubuntu-latest", "ubuntu-24.04-arm", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive }
      - uses: prefix-dev/setup-pixi@v0.8.14
        with: { pixi-version: v0.50.1 }
      - name: doctest
        shell: pixi run bash -e {0}
        run: pixi run -e ${{ matrix.environment }} doctest
